### ISSUE TITLE
能搞定设备间的自动获取吗？

### ISSUE THREAD

**Issue by dong-dong6** [wang-st/aliyunSignIn#2]
能搞定设备间的自动获取吗？

**Comment by wang-st** [comment]
自动获取什么

**Comment by dong-dong6** [comment]
设备间能量的收取

**Comment by dong-dong6** [comment]
![Uploading 719ece17350ccc606c93b0fbd11611b.jpg…]()

**Comment by dong-dong6** [comment]
![719ece17350ccc606c93b0fbd11611b](https://github.com/wang-st/aliyunSignIn/assets/73739354/c0d4e6a6-07d7-4730-85ce-98e8e43b8f92)

**Comment by dong-dong6** [comment]
以及这个地方的vip获取
![f078309a6cace30b6a683ad1fb9ceac](https://github.com/wang-st/aliyunSignIn/assets/73739354/9fa1c8e4-6c01-40be-b916-3d89a5801d18)
